### ISSUE TITLE
Cannot find -lrt and -lpthread during make build with "gcc-arm-none-eabi-10.3-2021.10" 

### ISSUE THREAD

**Issue by sunildogra1710** [eembc/coremark-pro#14] opened 2022-08-09 12:27 UTC
Hi,

Not able to make build with "gcc-arm-none-eabi-10.3-2021.10"

I changed gcc64.mak and common.mak file to add gcc-arm-none-eabi-10.3-2021.10 path. These files are present in util/make directory.

Changes mainly for below lines:
TOOLS	= ./coremark-pro-main/gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10
CC		= $(TOOLS)/bin/arm-none-eabi-gcc
AS		= $(TOOLS)/bin/arm-none-eabi-as
LD		= $(TOOLS)/bin/arm-none-eabi-gcc
AR		= $(TOOLS)/bin/arm-none-eabi-ar
INCLUDE = $(TOOLS)/arm-none-eabi/include

ARM gcc-arm-none-eabi-10.3-2021.10 package installed from ARM download link

Command= make TARGET=linux64 build-all

Error Message=
make[3]: Leaving directory `./coremark-pro-main/builds/linux64/gcc64/obj/bench/darkmark/zip'
./coremark-pro-main/gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gcc   -o./coremark-pro-main/builds/linux64/gcc64/bin/zip-test.exe zip-test.o ./coremark-pro-main/builds/linux64/gcc64/obj/bench/darkmark/zip/*.o  ./coremark-pro-main/builds/linux64/gcc64/obj/mith.a -lm -lrt -lpthread -lm -lrt -lpthread
./coremark-pro-main/gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: cannot find -lrt
./coremark-pro-main/gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: cannot find -lpthread
./coremark-pro-main/gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: cannot find -lrt
./coremark-pro-main/gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: cannot find -lpthread
collect2: error: ld returned 1 exit status
make[2]: *** [./coremark-pro-main/builds/linux64/gcc64/bin/zip-test.exe] Error 1
make[2]: Leaving directory `./coremark-pro-main/builds/linux64/gcc64/obj/workloads/zip-test'
make[1]: *** [build-all] Error 2
make[1]: Leaving directory `./coremark-pro-main'
make: *** [build] Error 2

Thanks,
SK

**Comment by petertorelli** [comment] 2022-08-09 15:32
`rt` is the POSIX realitime library (time functions), and `pthread` is the POSIX threading library. Neither of those come with the GCC Arm toolchain distribution. You will need to implement your own timing, most likely using a variant of `SysTick` from the BSP for your processor. As for threading, compile in single-thread mode: `-DUSE_NATIVE_PTHREAD=0 -DUSE_SINGLE_CONTEXT=1`, and remove those options from your makefile.

**Comment by sunildogra1710** [comment] 2022-08-10 05:05
As you suggested i used DUSE_NATIVE_PTHREAD=0 -DUSE_SINGLE_CONTEXT=1 and remove rt and pthread option from gcc64.mak.
Example: 
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gcc -c -g -O2 -DNDEBUG -DHOST_EXAMPLE_CODE=1 -std=gnu99   -DHAVE_SYS_STAT_H=1 **-DUSE_NATIVE_PTHREAD=0 -DUSE_SINGLE_CONTEXT=1** -DGCC_INLINE_MACRO=1 -DNO_RESTRICT_QUALIFIER=1 -DEE_SIZEOF_LONG=8 -DEE_SIZEOF_PTR=8 -DEE_PTR_ALIGN=8 -DHAVE_SYS_STAT_H=1 -DUSE_NATIVE_PTHREAD=0 -DUSE_SINGLE_CONTEXT=1 -DGCC_INLINE_MACRO=1 -DNO_RESTRICT_QUALIFIER=1 -DEE_SIZEOF_LONG=8 -DEE_SIZEOF_PTR=8 -DEE_PTR_ALIGN=8 -DEE_SIZEOF_INT=4 -DEE_SIZEOF_LONG=8  -Wall -Wno-long-long -fno-asm -fsigned-char      -I./mith/include -I./mith/al/include -I./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/arm-none-eabi/include -I./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/lib/gcc/arm-none-eabi/10.3.1/plugin/include -I./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/lib/gcc/arm-none-eabi/10.3.1/include -I./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/lib/gcc/arm-none-eabi/10.3.1/install-tools/include -I./mith/al/include ./workloads/zip-test/zip-test.c -o zip-test.o


Below command giving fee error. please comment 
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gcc -o./builds/linux64/gcc64/bin/zip-test.exe zip-test.o ./builds/linux64/gcc64/obj/bench/darkmark/zip/*.o ./builds/linux64/gcc64/obj/mith.a -lm

Error Message => 
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
exit.c:(.text.exit+0x2c): undefined reference to `_exit'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./builds/linux64/gcc64/obj/mith.a(th_lib.o): in function `th_aligned_malloc_x':
./mith/src/th_lib.c:851: undefined reference to `posix_memalign'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./builds/linux64/gcc64/obj/mith.a(th_al.o): in function `al_signal_start':
./mith/al/src/th_al.c:252: undefined reference to `clock_gettime'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./builds/linux64/gcc64/obj/mith.a(th_al.o): in function `al_signal_finished':
./mith/al/src/th_al.c:297: undefined reference to `clock_gettime'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./builds/linux64/gcc64/obj/mith.a(th_al.o): in function `al_signal_now':
./mith/al/src/th_al.c:334: undefined reference to `clock_gettime'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-fstatr.o): in function `_fstat_r':
fstatr.c:(.text._fstat_r+0x1c): undefined reference to `_fstat'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-openr.o): in function `_open_r':
openr.c:(.text._open_r+0x24): undefined reference to `_open'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-sbrkr.o): in function `_sbrk_r':
sbrkr.c:(.text._sbrk_r+0x18): undefined reference to `_sbrk'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-signalr.o): in function `_kill_r':
signalr.c:(.text._kill_r+0x1c): undefined reference to `_kill'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-signalr.o): in function `_getpid_r':
signalr.c:(.text._getpid_r+0x4): undefined reference to `_getpid'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-statr.o): in function `_stat_r':
statr.c:(.text._stat_r+0x1c): undefined reference to `_stat'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-unlinkr.o): in function `_unlink_r':
unlinkr.c:(.text._unlink_r+0x18): undefined reference to `_unlink'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-writer.o): in function `_write_r':
writer.c:(.text._write_r+0x24): undefined reference to `_write'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-closer.o): in function `_close_r':
closer.c:(.text._close_r+0x18): undefined reference to `_close'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-isattyr.o): in function `_isatty_r':
isattyr.c:(.text._isatty_r+0x18): undefined reference to `_isatty'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-linkr.o): in function `_link_r':
linkr.c:(.text._link_r+0x1c): undefined reference to `_link'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-lseekr.o): in function `_lseek_r':
lseekr.c:(.text._lseek_r+0x24): undefined reference to `_lseek'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-readr.o): in function `_read_r':
readr.c:(.text._read_r+0x24): undefined reference to `_read'
./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./gcc-arm/x86_64/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-abort.o): in function `abort':
abort.c:(.text.abort+0x10): undefined reference to `_exit'
collect2: error: ld returned 1 exit status

Thanks,
SK

**Comment by petertorelli** [comment] 2022-08-10 21:49
For everything except the three `th_`/`al_` functions, this is expected behavior. You are compiling a linux program on a baremetal compiler. `arm-none-eabi` does not have operating system support built in, which is why _link_r, _lseek, _exit, abort are not defined: those are part of the linux library. If you had used `arm-linux-eabi` then it would have compiled. This is unrelated to the benchmark. Here [is a good explanation](https://wiki-archive.linaro.org/WorkingGroups/ToolChain/FAQ#What_is_the_differences_between_.2BIBw-arm-none-eabi-.2BIB0_and_.2BIBw-arm-linux-gnueabihf.2BIB0.3F_Can_I_use_.2BIBw-arm-linux-gnueabihf.2BIB0_tool_chain_in_bare-metal_environment.3F_How_do_you_know_which_toolchain_binary_to_use_where.3F) of the three components in the toolchain name.

**Comment by petertorelli** [comment] 2022-08-26 16:33
Closing this since there has been no follow up.

**Closed as completed by petertorelli** 2022-08-26 16:33 UTC
