### ISSUE TITLE
for baremetal run, cjpeg macro variable SELECT_PRESET_ID is wrong

### ISSUE THREAD

**Issue by Rolfy360** [eembc/coremark-pro#3] opened 2020-03-18 05:55 UTC
hi there,
coremarkPro with cygwin TARGET=linux64 is ok to run,
but when I try to port package to bare-metal env. without file I/O, 
cjpeg always fail with "Cannot find file Rose256.bmp".

In "coremark-pro/workloads/cjpeg-rose7-preset/Makefile"
    line 5 export SELECT_PRESET_ID=0
in "coremark-pro/benchmarks/consumer_v2/cjpeg/bmark_lite.c"
    line 193-204
SELECT_PRESET_ID==1 maps to Rose256
SELECT_PRESET_ID==2 maps to goose
The mismatch cause failure.
(in cygwin, strace shows cjpeg-rose7-reset.exe uses file I/O system call to get data, not from internal preset buffer)

After correcting the Makefile, cjpeg is passed without error.

**Comment by petertorelli** [comment] 2020-03-18 17:35
**Status**
This has been confirmed as a bug.

**Severity**
Low. The change occurs outside the main benchmark timing loop, but see the caveats below.

**Impact**
The memory allocation is slightly different: the global variable version of the image is stored in the data segment and the dynamic comes from a heap malloc (assuming `th_malloc` is in the abstraction layer invokes the standard library function). Since it the global is unused in the pre-fix it may or may not be linked depending on the compiler/linker optimizations, which could impact the total footprint of the image. However, the impact of variable location or code footprint size appears inconsequential, and is mitigtated by the fact that one would need to specifically change the linker map file to move this data somewhere else (e.g., flash ex vs. sram  ex in the case of baremetal).

**Notes**
Thanks for identifying this. An update is forthcoming.

**Comment by petertorelli** [comment] 2020-03-18 17:40
Released in d5b4f2ba7ba31e37a5aa93423831e7d5eb933868.

**Closed by petertorelli** 2020-03-18 17:40 UTC
Labels: bug
